#%RAML 1.0
title: Weather REST Services API using Data Types
version: v1
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/cf99f9fe-dc6c-4748-a4f5-1809aee3a158/api/{version}
mediaType: application/json

securitySchemes:
  basicAuth:
    description: Each request must contain the headers necessary for
                 basic authentication
    type: Basic Authentication
    describedBy:
      headers:
        Authorization:
          description: Used to send the Base64-encoded "username:password"
                       credentials
          type: string
      responses:
        401:
          description: |
            Unauthorized. Either the provided username and password
            combination is invalid, or the user is not allowed to access
            the content provided by the requested URL.
            
traits: 
  -404ErrorResponseMessage:
      description: 404 error message for webservice
      responses:
        404:
         body: 
           application/json:
             example: { "message" : "Not found"}

  -400ErrorResponseMessage:          
      description: 400 error message for webservice
      responses:
        404:
         body: 
           application/json:
             example: { "message" : "Bad Request"}  
  -500ErrorResponseMessage:          
      description: 500 error message for webservice
      responses:
        404:
         body: 
           application/json:
             example: { "message" : "Internal Server Error"} 
             
/global-weather:     
  /cities-by-Country:
    get:
      description: Get All cities By Country
      queryParameters:
        countryName:
          description: "name of the country"
          required: true
      responses:
        200:
          body:
            application/json:
              example: !include Example_Json/citiesbycountry.json
        
      is: [-404ErrorResponseMessage , -400ErrorResponseMessage , -500ErrorResponseMessage]
            
       
    
  /weather:
    get:
      description: Get All cities By Country
      queryParameters:
        countryName:
          description: "name of the country"
          required: true
        cityName:
          description: "name of the city"
          required: true
    
      responses:
        200:
          body:
            application/json:
              example: !include Example_Json/cityweather.json
      is: [-404ErrorResponseMessage , -400ErrorResponseMessage , -500ErrorResponseMessage]
       